/**
 * Material scaffold tests.
 *
 * There is no GPU in the test environment, so these test everything that does
 * not need one — which is most of the module. `Material.create` is deliberately
 * thin: acquiring a device and calling `createRenderPipelineAsync` are the only
 * steps that require hardware, so the spec resolution, the code generation, the
 * validation, the uniform packing, and the cache keys are all pure and all
 * testable here.
 *
 * The bar is *shape*, not size. A scaffold that emits a plausible-looking but
 * subtly wrong program is worse than one that refuses to build, because the
 * failure surfaces three layers down as a driver message nobody can act on. So
 * the assertions are about what is guaranteed: the exact generated text, the
 * exact byte offsets, the exact error codes, and the exact determinism.
 *
 * The golden test is the highest-value test in this file. It pins the entire
 * generated program for one fully-specified material, so any accidental change
 * to the scaffold — a reordered field, a lost `@interpolate(flat)`, a renamed
 * entry point — shows up as a diff in a snapshot rather than as a regression
 * nobody notices until a frame renders wrong.
 */

import { describe, expect, test } from 'bun:test';
import { AseError } from '../src/core/error.ts';
import { BIND_GROUP, FRAME_BLOCK, OBJECT_BLOCK, RESERVED_SLOT_NAMES } from '../src/core/slot.ts';
import { POSITION_LAYOUT, STANDARD_LAYOUT, layout } from '../src/geometry/layout.ts';
import {
  basicMaterialSpec,
  checkVaryingBudget,
  describeMaterial,
  fnv1a,
  generateScaffold,
  pipelineKeyOf,
  removeComments,
  tokenKeyOf,
  pbrMaterialSpec,
  resolveSpec,
  stripComments,
  validateBodyIdentifiers,
  validateGeneratedWGSL,
} from '../src/material/index.ts';
import type { MaterialSpec } from '../src/material/index.ts';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Asserts that `fn` throws a catalog error with exactly this code. */
function expectError(fn: () => unknown, code: string): AseError {
  try {
    fn();
  } catch (err) {
    if (!(err instanceof AseError)) {
      throw new Error(`expected an AseError, got ${String(err)}`);
    }
    expect(err.code).toBe(code as AseError['code']);
    // Every error carries all five fields. If any is missing, the error is
    // useless to whoever has to act on it.
    expect(err.message.length).toBeGreaterThan(0);
    expect(err.why.length).toBeGreaterThan(0);
    expect(err.fix.length).toBeGreaterThan(0);
    expect(err.link).toContain('apse.dev');
    return err;
  }
  throw new Error(`expected code ${code} but nothing was thrown`);
}

/** The smallest valid spec, overridden per test. */
function spec(over: Partial<MaterialSpec> = {}): MaterialSpec {
  return {
    name: 't',
    varyings: { uv: 'vec2f' },
    vertex: 'out.clip = frame.viewProj * obj.model * vec4f(in.position, 1.0);',
    fragment: 'return vec4f(1.0);',
    ...over,
  };
}

const CHECKER: MaterialSpec = {
  name: 'checker',
  layout: STANDARD_LAYOUT,
  varyings: { worldPos: 'vec3f', uv: 'vec2f' },
  slots: { baseColor: { type: 'vec3f', default: [1, 0, 0] }, scale: 'f32' },
  textures: { albedo: { kind: '2d' } },
  phase: 'opaque',
  topology: 'triangle-list',
  cull: 'back',
  depth: { write: true, compare: 'less' },
  blend: null,
  targets: [{ format: 'bgra8unorm' }],
  vertex: `
out.clip = frame.viewProj * obj.model * vec4f(in.position, 1.0);
out.worldPos = (obj.model * vec4f(in.position, 1.0)).xyz;
out.uv = in.uv;
`,
  fragment: `
let base = textureSample(albedo, albedoSampler, in.uv) * vec4f(mat.baseColor, 1.0);
return vec4f(base.rgb * in.worldPos, 1.0);
`,
};

/**
 * The full generated program for {@link CHECKER}, pinned.
 *
 * Verified by eye to be valid WGSL: every struct field carries its trailing
 * comma; `MaterialData` is `vec3<f32>` at 0 with `f32` at 12, 16 bytes total;
 * `@builtin(position) clip` precedes the located varyings and consumes no
 * location; `wgslTextureDecl` places `albedo` at group 3 binding 0; and the two
 * entry points carry the attributes and signatures the pipeline asks for.
 */
const GOLDEN_WGSL = `// Generated by apse — material "checker". Do not edit: every
// declaration, binding, and signature below is produced from the spec.
// vertex   body may use: in, frame, obj, out, mat, albedo, albedoSampler
// fragment body may use: in, frame, obj, mat, albedo, albedoSampler
// ---------------------------------------------------------------------

// ---- uniform blocks ----
struct Frame {
  view : mat4x4<f32>,
  proj : mat4x4<f32>,
  viewProj : mat4x4<f32>,
  invView : mat4x4<f32>,
  invProj : mat4x4<f32>,
  invViewProj : mat4x4<f32>,
  camPos : vec3<f32>,
  time : f32,
  delta : f32,
  elapsed : f32,
  resolution : vec2<f32>,
  viewport : vec2<u32>,
  exposure : f32,
  alpha : f32,
};
struct ObjectData {
  model : mat4x4<f32>,
  normalMatrix : mat3x3<f32>,
  objectId : u32,
  instanceId : u32,
  visibility : f32,
};
struct MaterialData {
  baseColor : vec3<f32>,
  scale : f32,
};

// ---- vertex input (position:float32x3|normal:float32x3|uv:float32x2) ----
struct VertexIn {
  @location(0) position : vec3<f32>,
  @location(1) normal : vec3<f32>,
  @location(2) uv : vec2<f32>,
};

// ---- varyings ----
struct Varyings {
  @builtin(position) clip : vec4f,
  @location(0) worldPos : vec3f,
  @location(1) uv : vec2f,
};

// ---- bindings ----
@group(0) @binding(0) var<uniform> frame : Frame;
@group(1) @binding(0) var<uniform> obj : ObjectData;
@group(2) @binding(0) var<uniform> mat : MaterialData;
@group(3) @binding(0) var albedo : texture_2d<f32>;
@group(3) @binding(1) var albedoSampler : sampler;

// ---- generated by apse: vertex stage ----
@vertex
fn vs(in : VertexIn) -> Varyings {
  var out : Varyings;
  out.clip = frame.viewProj * obj.model * vec4f(in.position, 1.0);
  out.worldPos = (obj.model * vec4f(in.position, 1.0)).xyz;
  out.uv = in.uv;
  return out;
}

// ---- generated by apse: fragment stage ----
@fragment
fn fs(in : Varyings) -> @location(0) vec4f {
  let base = textureSample(albedo, albedoSampler, in.uv) * vec4f(mat.baseColor, 1.0);
  return vec4f(base.rgb * in.worldPos, 1.0);
}
`;

/**
 * A structural parse of generated WGSL.
 *
 * Not a WGSL parser — a check of the invariants a *generator* can violate while
 * producing text that looks entirely reasonable. Braces balance, every struct
 * field ends in a comma, every `@group(n)` matches `BIND_GROUP` and exposes the
 * variable the renderer's layouts are described against, and every
 * `frame.`/`obj.`/`mat.`/`in.`/`out.` access in the bodies resolves to a field
 * the spec actually declared.
 */
function parseCheck(s: MaterialSpec): string {
  const code = generateScaffold(s).code;
  const resolved = resolveSpec(s);

  // 1. Balanced braces.
  let depth = 0;
  for (const ch of code) {
    if (ch === '{') depth++;
    else if (ch === '}') depth--;
    expect(depth).toBeGreaterThanOrEqual(0);
  }
  expect(depth).toBe(0);

  // 2. Every struct field is comma-terminated.
  for (const m of code.matchAll(/struct (\w+) \{([^}]*)\}/g)) {
    for (const raw of m[2].split('\n')) {
      const line = raw.trim();
      if (line.length === 0) continue;
      expect(line.endsWith(',')).toBe(true);
    }
  }

  // 3. Group indices and variable names agree with BIND_GROUP.
  const expectedVar = new Map<number, string | null>([
    [BIND_GROUP.frame, 'frame'],
    [BIND_GROUP.object, 'obj'],
    [BIND_GROUP.material, resolved.materialBlock === null ? null : 'mat'],
    [BIND_GROUP.texture, null],
  ]);
  for (const m of code.matchAll(/@group\((\d+)\) @binding\((\d+)\) var(?:<(\w+)>)? (\w+)/g)) {
    const group = Number(m[1]);
    expect(expectedVar.has(group)).toBe(true);
    const want = expectedVar.get(group) ?? null;
    if (want !== null) expect(m[4]).toBe(want);
  }
  // Group 3 is the texture group and holds only textures and samplers.
  for (const m of code.matchAll(/@group\(3\) @binding\(\d+\) var (\w+)/g)) {
    const isTexture = resolved.textures.some((t) => t.varName === m[1]);
    const isSampler = resolved.samplers.some((s) => s.varName === m[1]);
    expect(isTexture || isSampler).toBe(true);
  }

  // 4. Every field access in either body resolves. `in` and `out` name
  // different containers in the two stages, which is exactly the thing a
  // reviewer cannot see in a generated file: in the vertex stage `in` is
  // VertexIn and `out` is Varyings; in the fragment stage `in` is Varyings and
  // `out` does not exist at all.
  const attributes = new Set(resolved.layout.attributes.map((a) => a.name));
  const varyings = new Set([...resolved.varyings.map((v) => v.name)]);
  const frameFields = new Set(FRAME_BLOCK.fields.map((f) => f.name));
  const objFields = new Set(OBJECT_BLOCK.fields.map((f) => f.name));
  const matFields = new Set(Object.keys(resolved.slotTypes));

  for (const [body, stage] of [
    [resolved.vertexBody, 'vertex'],
    [resolved.fragmentBody, 'fragment'],
  ] as [string, 'vertex' | 'fragment'][]) {
    for (const m of stripComments(body).matchAll(/\b(in|out|frame|obj|mat)\s*\.\s*(\w+)/g)) {
      const [, prefix, field] = m;
      if (prefix === 'in') {
        expect(stage === 'vertex' ? attributes.has(field) : varyings.has(field)).toBe(true);
      } else if (prefix === 'out') {
        expect(stage).toBe('vertex');
        expect(varyings.has(field)).toBe(true);
      } else if (prefix === 'frame') {
        expect(frameFields.has(field)).toBe(true);
      } else if (prefix === 'obj') {
        expect(objFields.has(field)).toBe(true);
      } else {
        expect(matFields.has(field)).toBe(true);
      }
    }
  }

  // The apse-side structural validator agrees.
  expect(validateGeneratedWGSL(code)).toEqual({ ok: true });
  return code;
}

// ---------------------------------------------------------------------------
// The golden snapshot
// ---------------------------------------------------------------------------

describe('generateScaffold — the golden snapshot', () => {
  test('the entire generated program for one fully-specified material is byte-exact', () => {
    expect(generateScaffold(CHECKER).code).toBe(GOLDEN_WGSL);
  });

  test('the golden program is structurally valid', () => {
    expect(parseCheck(CHECKER)).toBe(GOLDEN_WGSL);
  });

  test('the golden program declares no group the renderer does not know about', () => {
    const groups = [...GOLDEN_WGSL.matchAll(/@group\((\d+)\)/g)].map((m) => Number(m[1]));
    expect(new Set(groups)).toEqual(new Set([0, 1, 2, 3]));
    expect(BIND_GROUP).toEqual({ frame: 0, object: 1, material: 2, texture: 3 });
  });
});

// ---------------------------------------------------------------------------
// Generated declarations
// ---------------------------------------------------------------------------

describe('generateScaffold — generated declarations', () => {
  const code = generateScaffold(CHECKER).code;

  test('the VertexIn struct comes from the layout, with the right locations', () => {
    expect(code).toContain('struct VertexIn {');
    expect(code).toContain('  @location(0) position : vec3<f32>,');
    expect(code).toContain('  @location(1) normal : vec3<f32>,');
    expect(code).toContain('  @location(2) uv : vec2<f32>,');
  });

  test('the Varyings struct starts with the builtin position and then locates in order', () => {
    const block = code.slice(code.indexOf('struct Varyings {'), code.indexOf('};', code.indexOf('struct Varyings {')));
    const lines = block.split('\n').map((l) => l.trim()).filter((l) => l.length > 0);
    expect(lines[1]).toBe('@builtin(position) clip : vec4f,');
    expect(lines[2]).toBe('@location(0) worldPos : vec3f,');
    expect(lines[3]).toBe('@location(1) uv : vec2f,');
  });

  test('the three uniform blocks are present and named', () => {
    expect(code).toContain('struct Frame {');
    expect(code).toContain('struct ObjectData {');
    expect(code).toContain('struct MaterialData {');
    // And they are the same blocks the uniform machinery produces, so the
    // generated WGSL and the JS packing cannot drift.
    expect(code).toContain(FRAME_BLOCK.wgsl);
    expect(code).toContain(OBJECT_BLOCK.wgsl);
  });

  test('the reserved bindings are at the groups BIND_GROUP fixes', () => {
    expect(code).toContain('@group(0) @binding(0) var<uniform> frame : Frame;');
    expect(code).toContain('@group(1) @binding(0) var<uniform> obj : ObjectData;');
    expect(code).toContain('@group(2) @binding(0) var<uniform> mat : MaterialData;');
  });

  test('the material struct holds the declared slots in declaration order', () => {
    const block = code.slice(code.indexOf('struct MaterialData {'));
    expect(block).toContain('  baseColor : vec3<f32>,');
    expect(block).toContain('  scale : f32,');
    expect(block.indexOf('baseColor')).toBeLessThan(block.indexOf('scale'));
  });

  test('the texture binding uses the slot name, and the sampler follows it', () => {
    expect(code).toContain('@group(3) @binding(0) var albedo : texture_2d<f32>;');
    expect(code).toContain('@group(3) @binding(1) var albedoSampler : sampler;');
  });

  test('the entry points carry the attributes and signatures the pipeline asks for', () => {
    expect(code).toContain('@vertex\nfn vs(in : VertexIn) -> Varyings {');
    expect(code).toContain('@fragment\nfn fs(in : Varyings) -> @location(0) vec4f {');
    // `out` is declared by apse, not by the user, and returned by apse.
    expect(code).toContain('  var out : Varyings;');
  });

  test('the header names what each body may use', () => {
    expect(code).toContain('vertex   body may use: in, frame, obj, out, mat, albedo, albedoSampler');
    expect(code).toContain('fragment body may use: in, frame, obj, mat, albedo, albedoSampler');
  });

  test('a material with no slots omits the mat binding entirely', () => {
    const bare = generateScaffold(spec()).code;
    expect(bare).not.toContain('struct MaterialData');
    expect(bare).not.toContain('var<uniform> mat');
    expect(bare).toContain('@group(0) @binding(0) var<uniform> frame : Frame;');
    // The texture group keeps its index even when group 2 is empty, which is
    // why the layouts are positional and fixed.
    expect(bare).not.toContain('@group(3)');
  });

  test('a material with textures but no slots still binds group 3', () => {
    const s = generateScaffold(spec({ textures: { albedo: { kind: '2d' } } })).code;
    expect(s).not.toContain('var<uniform> mat');
    expect(s).toContain('@group(3) @binding(0) var albedo : texture_2d<f32>;');
    expect(s).toContain('@group(3) @binding(1) var albedoSampler : sampler;');
  });

  test('the prelude is spliced in after the declarations and before the entry points', () => {
    const s = spec({ prelude: 'fn helper(x: f32) -> f32 { return x * 2.0; }' });
    const code = generateScaffold(s).code;
    expect(code).toContain('fn helper(x: f32) -> f32 { return x * 2.0; }');
    expect(code.indexOf('fn helper')).toBeGreaterThan(code.indexOf('// ---- bindings ----'));
    expect(code.indexOf('fn helper')).toBeLessThan(code.indexOf('@vertex'));
  });

  test('byteLength and GeneratedShader carry the block specs', () => {
    const g = generateScaffold(CHECKER);
    expect(g.byteLength).toBe(GOLDEN_WGSL.length);
    expect(g.frameBlock).toBe(FRAME_BLOCK);
    expect(g.objectBlock).toBe(OBJECT_BLOCK);
    expect(g.materialBlock.structName).toBe('MaterialData');
    expect(g.slotTypes).toEqual({ baseColor: 'vec3f', scale: 'f32' });
    expect(g.textureSlots.map((t) => t.bindingIndex)).toEqual([0]);
  });
});

// ---------------------------------------------------------------------------
// Determinism
// ---------------------------------------------------------------------------

describe('generateScaffold — determinism', () => {
  test('the same spec produces byte-identical output, every time', () => {
    const a = generateScaffold(CHECKER).code;
    const b = generateScaffold(CHECKER).code;
    const c = generateScaffold({ ...CHECKER }).code;
    expect(b).toBe(a);
    expect(c).toBe(a);
  });

  test('resolution is memoised, so a spec object resolves to one identity', () => {
    expect(resolveSpec(CHECKER)).toBe(resolveSpec(CHECKER));
  });

  test('declaration order is significant, and reversing it changes the program', () => {
    // Varying and slot order determines @location and byte offset respectively.
    // If it were not significant, a material could be reordered by accident and
    // silently read the wrong data.
    const a = generateScaffold(spec({ varyings: { x: 'vec2f', y: 'vec2f' } })).code;
    const b = generateScaffold(spec({ varyings: { y: 'vec2f', x: 'vec2f' } })).code;
    expect(a).not.toBe(b);
  });

  test('an unrelated spec object does not contaminate the memo', () => {
    const a = generateScaffold(spec({ name: 'a' })).code;
    const b = generateScaffold(spec({ name: 'b' })).code;
    const c = generateScaffold(spec({ name: 'a' })).code;
    expect(a).toBe(c);
    expect(a).not.toBe(b);
  });
});

// ---------------------------------------------------------------------------
// Body validation
// ---------------------------------------------------------------------------

describe('generateScaffold — body validation', () => {
  test('a function declaration is rejected, and the fix names the escape hatch', () => {
    const err = expectError(
      () => generateScaffold(spec({ fragment: 'fn helper() -> f32 { return 1.0; }\nreturn vec4f(1.0);' })),
      'SHADER_BODY_INVALID',
    );
    expect(err.message).toContain('declares a function');
    expect(err.fix).toContain('prelude');
  });

  test('@group in a body is rejected — apse owns every binding', () => {
    const err = expectError(
      () => generateScaffold(spec({ fragment: '@group(1) @binding(0) var<uniform> mine : mat4x4f;\nreturn vec4f(1.0);' })),
      'SHADER_BODY_INVALID',
    );
    expect(err.message).toContain('@group');
    expect(err.why).toContain('bind group layout');
  });

  test('@binding, @builtin, @location and struct declarations are all rejected', () => {
    for (const body of [
      '@binding(0) var x : f32;\nreturn vec4f(1.0);',
      '@builtin(position) var x : vec4f;\nreturn vec4f(1.0);',
      '@location(0) var x : f32;\nreturn vec4f(1.0);',
      'struct Mine { a : f32, }\nreturn vec4f(1.0);',
    ]) {
      expectError(() => generateScaffold(spec({ fragment: body })), 'SHADER_BODY_INVALID');
    }
  });

  test('an @vertex/@fragment attribute in a body is rejected', () => {
    expectError(() => generateScaffold(spec({ fragment: '@fragment\nreturn vec4f(1.0);' })), 'SHADER_BODY_INVALID');
  });

  test('a vertex body that never assigns out.clip is rejected, and says so', () => {
    // This is the single most common mistake: everything compiles, every
    // triangle is silently discarded, and Dawn says nothing.
    const err = expectError(
      () => generateScaffold(spec({ vertex: 'out.uv = in.uv;' })),
      'SHADER_BODY_INVALID',
    );
    expect(err.message).toContain('out.clip');
    expect(err.fix).toContain('out.clip = frame.viewProj');
  });

  test('an empty body is rejected on both stages', () => {
    expectError(() => generateScaffold(spec({ vertex: '   \n  ' })), 'SHADER_BODY_INVALID');
    expectError(() => generateScaffold(spec({ fragment: '' })), 'SHADER_BODY_INVALID');
  });

  test('a fragment body that never returns is rejected', () => {
    const err = expectError(() => generateScaffold(spec({ fragment: 'let x = 1.0;' })), 'SHADER_BODY_INVALID');
    expect(err.message).toContain('never returns');
  });

  test('writing to out in the fragment stage is rejected', () => {
    const err = expectError(() => generateScaffold(spec({ fragment: 'out.uv = in.uv;\nreturn vec4f(1.0);' })), 'SHADER_BODY_INVALID');
    expect(err.message).toContain('`out`');
  });

  test('declarations inside a comment are not a false positive', () => {
    // Comments are stripped before scanning, so prose about `fn` and `@group`
    // does not trip the validator. This matters: the pbr material's body is
    // full of comments explaining the rules.
    const code = generateScaffold(spec({
      vertex: '// out.clip = frame.viewProj * obj.model;\nout.clip = frame.viewProj * obj.model * vec4f(in.position, 1.0);',
      fragment: '/* a fn would go in prelude, and @group is apse\'s */\nreturn vec4f(1.0);',
    })).code;
    expect(code).toContain('return vec4f(1.0);');
  });

  test('stripComments preserves line numbers and length', () => {
    const src = 'a\n// one\nb /* two\nthree */\nc';
    const out = stripComments(src);
    expect(out.split('\n').length).toBe(src.split('\n').length);
    expect(out.length).toBe(src.length);
    expect(out).toContain('a');
    expect(out).toContain('b');
    expect(out).toContain('c');
  });
});

// ---------------------------------------------------------------------------
// Identifier validation — the agent guard
// ---------------------------------------------------------------------------

describe('validateBodyIdentifiers — undeclared field is a typed error, not a WGSL one', () => {
  test('a typo in a frame field is caught and suggests the real one', () => {
    const err = expectError(
      () => generateScaffold(spec({ fragment: 'let v = frame.viewProjj;\nreturn vec4f(1.0);' })),
      'SHADER_BODY_INVALID',
    );
    expect(err.message).toContain('frame.viewProjj');
    expect(err.fix).toContain('frame.viewProj');
    expect(err.fix).toContain('camPos');
  });

  test('a hallucinated obj field is caught, and every real field is listed', () => {
    // Not a typo, so no suggestion — the useful answer is the full inventory.
    const err = expectError(
      () => generateScaffold(spec({ vertex: 'out.clip = frame.viewProj * obj.worldMatrix * vec4f(in.position, 1.0);' })),
      'SHADER_BODY_INVALID',
    );
    expect(err.message).toContain('obj.worldMatrix');
    for (const f of OBJECT_BLOCK.fields.map((x) => x.name)) expect(err.fix).toContain(f);
  });

  test('a material with no slots tells you to declare one, rather than listing nothing', () => {
    const err = expectError(() => generateScaffold(spec({ fragment: 'return vec4f(mat.tint);' })), 'SHADER_BODY_INVALID');
    expect(err.fix).toContain("slots:");
  });

  test('a slot the material never declared is caught', () => {
    const err = expectError(
      () => generateScaffold(spec({ slots: { tint: 'vec3f' }, fragment: 'return vec4f(mat.albedo);' })),
      'SHADER_BODY_INVALID',
    );
    expect(err.message).toContain('mat.albedo');
    expect(err.fix).toContain('Available on mat: tint');
  });

  test('a varying the material never declared is caught on out and on in', () => {
    const err = expectError(() => generateScaffold(spec({ vertex: 'out.clip = vec4f(in.position, 1.0); out.tangent = in.normal;' })), 'SHADER_BODY_INVALID');
    expect(err.message).toContain('out.tangent');
    const err2 = expectError(() => generateScaffold(spec({ fragment: 'return vec4f(in.tangent, 1.0);' })), 'SHADER_BODY_INVALID');
    expect(err2.message).toContain('in.tangent');
  });

  test('an attribute the layout does not have is caught in the vertex stage', () => {
    const err = expectError(() => generateScaffold(spec({ vertex: 'out.clip = vec4f(in.tangent, 1.0);' })), 'SHADER_BODY_INVALID');
    expect(err.message).toContain('in.tangent');
  });

  test('a body naming a deduplicated sampler is told the right name', () => {
    // Two slots, one shared sampler. The body must use the group's name.
    const s = spec({
      textures: { albedo: { kind: '2d' }, normalMap: { kind: '2d' } },
      fragment: 'let a = textureSample(normalMap, normalMapSampler, in.uv);\nreturn vec4f(a.rgb);',
    });
    const err = expectError(() => generateScaffold(s), 'SHADER_BODY_INVALID');
    expect(err.message).toContain('normalMapSampler');
    expect(err.fix).toContain('albedoSampler');
  });

  test('a non-texture member on a texture variable is rejected', () => {
    const err = expectError(
      () => generateScaffold(spec({ textures: { albedo: { kind: '2d' } }, fragment: 'let a = albedo.width;\nreturn vec4f(1.0);' })),
      'SHADER_BODY_INVALID',
    );
    expect(err.message).toContain('albedo.width');
  });

  test('legitimate texture builtin members are not rejected', () => {
    expect(() => generateScaffold(spec({
      textures: { albedo: { kind: '2d' } },
      fragment: 'let d = vec2f(textureDimensions(albedo));\nlet a = textureSample(albedo, albedoSampler, in.uv * d);\nreturn vec4f(a.rgb);',
    }))).not.toThrow();
  });

  test('validateBodyIdentifiers is exported and callable on its own', () => {
    const s = spec({ slots: { tint: 'vec3f' } });
    const r = resolveSpec(s);
    expect(() => validateBodyIdentifiers('return vec4f(mat.tint);', r, 'fragment', 't')).not.toThrow();
    expectError(() => validateBodyIdentifiers('return vec4f(mat.missing);', r, 'fragment', 't'), 'SHADER_BODY_INVALID');
  });

  test('local variables named like a reserved prefix are not confused for one', () => {
    // A local `mat4` or `obj2` must not trip the scan; only the exact reserved
    // prefixes followed by `.field` do.
    expect(() => generateScaffold(spec({
      slots: { tint: 'vec3f' },
      fragment: 'let frame2 = mat.tint;\nlet inner = 1.0;\nreturn vec4f(frame2 * f32(inner));',
    }))).not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// Varyings
// ---------------------------------------------------------------------------

describe('varyings', () => {
  test('locations are assigned in declaration order from 0, and clip takes none', () => {
    const r = resolveSpec(spec({ varyings: { a: 'f32', b: 'vec2f', c: 'vec4f' } }));
    expect(r.varyings[0]).toMatchObject({ name: 'clip', location: -1 });
    expect(r.varyings.slice(1).map((v) => [v.name, v.location])).toEqual([['a', 0], ['b', 1], ['c', 2]]);
  });

  test('integer varyings are emitted @interpolate(flat), because flat is mandatory', () => {
    // WGSL rejects an integer varying without it. This is the single easiest
    // trap in the whole module, and apse removes it by construction.
    const code = generateScaffold(spec({ varyings: { id: 'u32' } })).code;
    expect(code).toContain('@location(0) @interpolate(flat) id : u32,');
  });

  test('mat4x4f is flat too; float and vecN are not', () => {
    const code = generateScaffold(spec({
      varyings: { x: 'f32', p: 'vec3f', m: 'mat4x4f', s: 'i32' },
    })).code;
    expect(code).toContain('@location(0) x : f32,');
    expect(code).toContain('@location(1) p : vec3f,');
    expect(code).toContain('@location(2) @interpolate(flat) m : mat4x4f,');
    expect(code).toContain('@location(3) @interpolate(flat) s : i32,');
  });

  test('a varying type that cannot cross the rasteriser is rejected by name', () => {
    const err = expectError(() => generateScaffold(spec({ varyings: { bad: 'vec3u' as never } })), 'VARYING_TYPE_UNSUPPORTED');
    expect(err.fix).toContain('vec3f');
    expectError(() => generateScaffold(spec({ varyings: { bad: 'mat3x3f' as never } })), 'VARYING_TYPE_UNSUPPORTED');
  });

  test('17 varyings exceeds the inter-stage budget', () => {
    // 15 on the core profile, 14 in compatibility — because
    // @builtin(position) is one of the fragment stage's input variables even
    // though it consumes no location.
    const many: Record<string, 'f32'> = {};
    for (let i = 0; i < 17; i++) many[`v${i}`] = 'f32';
    const err = expectError(() => generateScaffold(spec({ varyings: many })), 'VARYING_TOO_MANY');
    expect(err.message).toContain('17');
    expect(err.why).toContain('@builtin(position)');
    expect(err.fix).toContain('15');
  });

  test('exactly 15 user varyings is the limit, and 16 is not', () => {
    const at: Record<string, 'f32'> = {};
    for (let i = 0; i < 15; i++) at[`v${i}`] = 'f32';
    expect(() => generateScaffold(spec({ varyings: at }))).not.toThrow();
    at.v15 = 'f32';
    expectError(() => generateScaffold(spec({ varyings: at })), 'VARYING_TOO_MANY');
  });

  test('the device limit tightens the check when the device is reachable', () => {
    const r = resolveSpec(spec({ varyings: { a: 'f32', b: 'f32' } }));
    expect(() => checkVaryingBudget(r)).not.toThrow();
    expectError(() => checkVaryingBudget(r, { maxInterStageShaderVariables: 2 }), 'VARYING_TOO_MANY');
  });

  test('the component budget is checked as well as the variable count', () => {
    // Four mat4x4f varyings is 64 components, over the 56 left after position.
    const r = resolveSpec(spec({ varyings: { a: 'mat4x4f', b: 'mat4x4f', c: 'mat4x4f', d: 'mat4x4f' } }));
    const err = expectError(() => checkVaryingBudget(r), 'VARYING_TOO_MANY');
    expect(err.message).toContain('components');
  });

  test('a varying named clip is rejected — the builtin owns it', () => {
    expectError(() => generateScaffold(spec({ varyings: { clip: 'vec3f' } })), 'VARYING_TYPE_UNSUPPORTED');
  });
});

// ---------------------------------------------------------------------------
// Slots and reserved names
// ---------------------------------------------------------------------------

describe('slots', () => {
  test('a slot named after an obj field is rejected', () => {
    const err = expectError(() => generateScaffold(spec({ slots: { model: 'f32' } })), 'OPTION_UNKNOWN');
    expect(err.message).toContain('"model"');
    expect(err.fix).toContain('normalMatrix');
  });

  test('a slot named after a frame field is rejected', () => {
    // `view` is the classic: a user reaching for a frame field and getting a
    // material slot instead would read stale per-material data.
    const err = expectError(() => generateScaffold(spec({ slots: { view: 'f32' } })), 'OPTION_UNKNOWN');
    expect(err.message).toContain('"view"');
  });

  test('every reserved name is protected, both halves of the blocks', () => {
    for (const name of RESERVED_SLOT_NAMES) {
      expectError(() => generateScaffold(spec({ slots: { [name]: 'f32' } })), 'OPTION_UNKNOWN');
    }
    // 19 names: 5 object fields and 14 frame fields.
    expect(RESERVED_SLOT_NAMES.size).toBe(19);
  });

  test('a default with the wrong component count is rejected', () => {
    const err = expectError(
      () => generateScaffold(spec({ slots: { color: { type: 'vec3f', default: [1, 0] } } })),
      'SLOT_DEFAULT_INVALID',
    );
    expect(err.message).toContain('3-component');
    expect(err.fix).toContain('exactly 3 numbers');
  });

  test('a non-finite default is rejected, because it blanks every fragment', () => {
    expectError(() => generateScaffold(spec({ slots: { x: { type: 'f32', default: NaN } } })), 'SLOT_DEFAULT_INVALID');
    expectError(() => generateScaffold(spec({ slots: { c: { type: 'vec3f', default: [1, 0, Infinity] } } })), 'SLOT_DEFAULT_INVALID');
  });

  test('an unknown slot type is rejected', () => {
    expectError(() => generateScaffold(spec({ slots: { x: 'vec7f' as never } })), 'SLOT_TYPE_UNKNOWN');
  });

  test('an unknown spec option is rejected, so a typo never fails silently', () => {
    const err = expectError(() => generateScaffold(spec({ varing: { uv: 'vec2f' } } as never)), 'OPTION_UNKNOWN');
    expect(err.message).toContain('varing');
    expect(err.fix).toContain('varyings');
  });

  test('a slot name that is not a usable WGSL identifier is rejected', () => {
    expectError(() => generateScaffold(spec({ slots: { 'my-color': 'f32' } })), 'OPTION_UNKNOWN');
    expectError(() => generateScaffold(spec({ slots: { '1st': 'f32' } })), 'OPTION_UNKNOWN');
    expectError(() => generateScaffold(spec({ slots: { fn: 'f32' } })), 'OPTION_UNKNOWN');
  });

  test('both slot spellings resolve to the same type map and the same program', () => {
    const short = generateScaffold(spec({ slots: { x: 'f32' } })).code;
    const long = generateScaffold(spec({ slots: { x: { type: 'f32' } } })).code;
    expect(short).toBe(long);
  });

  test('more than one colour target is rejected, and says why', () => {
    const err = expectError(
      () => generateScaffold(spec({ targets: [{ format: 'rgba8unorm' }, { format: 'rgba16float' }] })),
      'RENDER_TARGET_FORMAT_MISMATCH',
    );
    expect(err.message).toContain('one colour');
    expectError(() => generateScaffold(spec({ targets: [] })), 'RENDER_TARGET_FORMAT_MISMATCH');
  });
});

// ---------------------------------------------------------------------------
// Uniform offsets — the vec3 padding rule
// ---------------------------------------------------------------------------

describe('uniform offsets', () => {
  test('a vec3f is 16-byte aligned but only 12 wide, so the next field moves to 16', () => {
    // This is a real bug class. `vec3<f32>` in the *uniform* address space is
    // aligned to 16 but occupies 12, and the following member starts at the
    // next 16-byte boundary. Getting this wrong writes `c` on top of the third
    // component of `b`, and the symptom is a slowly wrong colour, not a crash.
    const g = generateScaffold(spec({ slots: { a: 'f32', b: 'vec3f', c: 'f32' } }));
    const off = Object.fromEntries(g.materialBlock.fields.map((f) => [f.name, f.offset]));
    expect(off).toEqual({ a: 0, b: 16, c: 28 });
    expect(g.materialBlock.size).toBe(32);
  });

  test('the generated struct and the offsets come from the same builder', () => {
    const g = generateScaffold(spec({ slots: { a: 'f32', b: 'vec3f', c: 'f32' } }));
    // The WGSL is `buildUniformBlock`'s, not a hand-written template, which is
    // the only reason the two can be trusted to agree.
    expect(g.code).toContain(g.materialBlock.wgsl);
    expect(g.materialBlock.wgsl).toBe('struct MaterialData {\n  a : f32,\n  b : vec3<f32>,\n  c : f32,\n};');
  });

  test('a mat3x3f costs 48 bytes because each of its 3 columns is 16-aligned', () => {
    const g = generateScaffold(spec({ slots: { m: 'mat3x3f', x: 'f32' } }));
    const off = Object.fromEntries(g.materialBlock.fields.map((f) => [f.name, f.offset]));
    expect(off).toEqual({ m: 0, x: 48 });
    expect(g.materialBlock.size).toBe(64);
  });

  test('vec4f packs tightly; vec2f aligns to 8', () => {
    const g = generateScaffold(spec({ slots: { a: 'f32', b: 'vec4f', c: 'f32', d: 'vec2f' } }));
    const off = Object.fromEntries(g.materialBlock.fields.map((f) => [f.name, f.offset]));
    expect(off).toEqual({ a: 0, b: 16, c: 32, d: 40 });
  });

  test('the object block is dynamic, so it carries a 256-byte stride', () => {
    expect(OBJECT_BLOCK.stride % 256).toBe(0);
    expect(OBJECT_BLOCK.stride).toBeGreaterThanOrEqual(OBJECT_BLOCK.size);
  });
});

// ---------------------------------------------------------------------------
// Texture bindings and sampler sharing
// ---------------------------------------------------------------------------

describe('texture bindings', () => {
  test('two slots with the same sampler config share ONE sampler binding', () => {
    // A sampler is immutable state with no per-texture data, so N textures with
    // one config need one GPUSampler and one binding, not N.
    const g = generateScaffold(spec({ textures: { albedo: { kind: '2d' }, normalMap: { kind: '2d' } } }));
    const r = g.resolved;

    expect(g.textureSlots.map((t) => [t.varName, t.bindingIndex])).toEqual([['albedo', 0], ['normalMap', 1]]);
    expect(r.samplers.length).toBe(1);
    expect(r.samplers[0].bindingIndex).toBe(2);
    expect(r.samplers[0].slotNames).toEqual(['albedo', 'normalMap']);
    // Both slots are told to use the one name.
    expect(r.samplerForSlot.get('albedo')?.varName).toBe('albedoSampler');
    expect(r.samplerForSlot.get('normalMap')?.varName).toBe('albedoSampler');

    // So group 3 holds 3 bindings, not 4.
    const group3 = g.code.split('\n').filter((l) => l.includes('@group(3)'));
    expect(group3.length).toBe(3);
  });

  test('different address modes produce different samplers', () => {
    const r = resolveSpec(spec({
      textures: { repeat: { kind: '2d' }, clamp: { kind: '2d', addressMode: 'clamp-to-edge' } },
    }));
    expect(r.samplers.length).toBe(2);
    expect(r.samplers.map((s) => s.bindingIndex)).toEqual([2, 3]);
  });

  test('a comparison sampler is its own group and gets the comparison WGSL type', () => {
    // This is what pbr uses for its shadow map, alongside a filtering sampler
    // for albedo: two distinct configurations, so two bindings, both correct.
    const r = resolveSpec(spec({
      textures: {
        albedo: { kind: '2d' },
        shadowDepth: { kind: 'depth-2d', sampleType: 'depth', compare: true, mipmapFilter: false },
      },
    }));
    expect(r.samplers.map((s) => s.wgslType)).toEqual(['sampler', 'sampler_comparison']);
    expect(r.samplers.map((s) => s.layoutType)).toEqual(['filtering', 'comparison']);
    expect(r.samplers[0].addressMode).toBe('repeat');
    expect(r.samplers[1].addressMode).toBe('clamp-to-edge');
  });

  test('a texture binding index is assigned in declaration order', () => {
    const g = generateScaffold(spec({
      textures: { a: { kind: '2d' }, b: { kind: '2d' }, c: { kind: '2d' } },
    }));
    expect(g.textureSlots.map((t) => t.bindingIndex)).toEqual([0, 1, 2]);
  });

  test('an unsupported kind is rejected, and the message lists the supported ones', () => {
    const err = expectError(() => generateScaffold(spec({ textures: { x: { kind: '1d' as never } } })), 'TEXTURE_SLOT_TYPE_INVALID');
    expect(err.fix).toContain('depth-2d');
  });

  test('compare: true on a non-depth texture is rejected at spec time', () => {
    // WGSL rejects textureSampleCompare on a non-depth texture, but the message
    // would point into generated code. This points at the spec instead.
    expectError(
      () => generateScaffold(spec({ textures: { x: { kind: '2d', compare: true } } })),
      'TEXTURE_SLOT_TYPE_INVALID',
    );
  });

  test('a texture variable name that collides with a generated sampler is rejected', () => {
    const err = expectError(
      () => generateScaffold(spec({ textures: { tex: { kind: '2d' }, texSampler: { kind: '2d' } } })),
      'OPTION_UNKNOWN',
    );
    expect(err.message).toContain('collides');
  });

  test('a texture slot name override changes the shader variable but not the slot', () => {
    const g = generateScaffold(spec({ textures: { 'albedo-map': { kind: '2d', name: 'albedo' } } }));
    expect(g.code).toContain('@group(3) @binding(0) var albedo : texture_2d<f32>;');
    expect(g.textureSlots[0].slotName).toBe('albedo-map');
  });
});

// ---------------------------------------------------------------------------
// Cache keys
// ---------------------------------------------------------------------------

describe('cache keys', () => {
  // The reasoning, stated once so the assertions below can be short.
  //
  // There are two different questions and they have two different answers.
  //
  //   "Can these two materials share a GPUBindGroupLayout / GPUPipelineLayout?"
  //   YES whenever their *declarations* match — layout, varyings, slot types,
  //   texture kinds. Their shader statements are irrelevant to what has to be
  //   bound. So this key excludes the body, and two materials that differ only
  //   in how they shade get one shared layout object. This is where the win is:
  //   a scene of 500 materials should own 4 bind group layouts, not 2000.
  //
  //   "Is this the same compiled program?"
  //   YES only when the generated bytes match. A GPURenderPipeline is a linked
  //   shader module plus fixed-function state; two materials with different
  //   bodies have different modules, and sharing one pipeline would render one
  //   of them with the other's code — silently, with no WebGPU diagnostic and
  //   a plausible-looking frame. So this key includes the body.
  //
  // Conflating them into one key would either lose the layout sharing or, more
  // dangerously, "optimise" away a correctness bug.

  test('two specs differing only in the shader body share a pipeline STATE key', () => {
    // Bind group layouts are determined by declarations, not by statements.
    const a = generateScaffold(spec({ fragment: 'return vec4f(1.0, 0.0, 0.0, 1.0);' }));
    const b = generateScaffold(spec({ fragment: 'return vec4f(0.0, 1.0, 0.0, 1.0);' }));
    expect(a.pipelineStateKey).toBe(b.pipelineStateKey);
  });

  test('...but NOT a pipeline key, because the compiled programs differ', () => {
    // The other half of the same decision. If this ever became equal, one of two
    // materials would be drawn with the other's shader.
    const a = generateScaffold(spec({ fragment: 'return vec4f(1.0, 0.0, 0.0, 1.0);' }));
    const b = generateScaffold(spec({ fragment: 'return vec4f(0.0, 1.0, 0.0, 1.0);' }));
    expect(a.pipelineKey).not.toBe(b.pipelineKey);
  });

  test('two specs differing in cull differ in BOTH keys', () => {
    const a = generateScaffold(spec({ cull: 'back' }));
    const b = generateScaffold(spec({ cull: 'none' }));
    expect(a.pipelineStateKey).not.toBe(b.pipelineStateKey);
    expect(a.pipelineKey).not.toBe(b.pipelineKey);
  });

  test('every fixed-function field participates in the state key', () => {
    const base = generateScaffold(spec()).pipelineStateKey;
    const variants: [string, Partial<MaterialSpec>][] = [
      ['topology', { topology: 'triangle-strip' }],
      ['cull', { cull: 'front' }],
      ['frontFace', { frontFace: 'cw' }],
      ['depth.write', { depth: { write: false, compare: 'less' } }],
      ['depth.compare', { depth: { write: true, compare: 'less-equal' } }],
      ['blend', { blend: { color: { srcFactor: 'one', dstFactor: 'zero', operation: 'add' }, alpha: { srcFactor: 'one', dstFactor: 'zero', operation: 'add' } } }],
      ['target format', { targets: [{ format: 'bgra8unorm' }] }],
      ['sampleCount', { sampleCount: 4 }],
      ['depthFormat', { depthFormat: 'depth32float' }],
    ];
    for (const [label, over] of variants) {
      expect(`${label}:${generateScaffold(spec(over)).pipelineStateKey}`).not.toBe(`${label}:${base}`);
    }
  });

  test('every structural declaration participates in the state key', () => {
    const base = generateScaffold(spec()).pipelineStateKey;
    const variants: [string, Partial<MaterialSpec>][] = [
      ['layout', { layout: POSITION_LAYOUT }],
      ['varyings', { varyings: { uv: 'vec2f', extra: 'f32' } }],
      ['slots', { slots: { tint: 'vec3f' } }],
      ['textures', { textures: { albedo: { kind: '2d' } } }],
      ['texture kind', { textures: { albedo: { kind: 'cube' } } }],
    ];
    for (const [label, over] of variants) {
      expect(`${label}:${generateScaffold(spec(over)).pipelineStateKey}`).not.toBe(`${label}:${base}`);
    }
  });

  test('the slot name is part of the state key, not just the slot type', () => {
    // `mat.x` and `mat.y` are the same shape and must not share a layout, or
    // one would read the other's field.
    const a = generateScaffold(spec({ slots: { x: 'f32' } })).pipelineStateKey;
    const b = generateScaffold(spec({ slots: { y: 'f32' } })).pipelineStateKey;
    expect(a).not.toBe(b);
  });

  test('the state key is a 32-bit integer, so a lookup is an integer compare', () => {
    const k = generateScaffold(spec()).pipelineStateKey;
    expect(Number.isInteger(k)).toBe(true);
    expect(k).toBeGreaterThanOrEqual(0);
    expect(k).toBeLessThanOrEqual(0xffffffff);
  });

  test('fnv1a is order-sensitive and field-separator aware', () => {
    // ["ab","c"] and ["a","bc"] must not collide, or a field boundary could be
    // moved without changing the key.
    expect(fnv1a('ab', 'c')).not.toBe(fnv1a('a', 'bc'));
    expect(fnv1a('a', 'b')).not.toBe(fnv1a('b', 'a'));
    expect(fnv1a('a')).toBe(fnv1a('a'));
  });

  test('the pipeline key is the state key plus the code, and nothing else', () => {
    const g = generateScaffold(spec());
    expect(pipelineKeyOf(g.resolved, g.code)).toBe(g.pipelineKey);
  });

  test('materials differing only in name or comments SHARE a pipeline', () => {
    // The regression this guards: the generated header carries the material
    // name, and bodies are commented. If the key hashed raw text, every
    // material would be its own pipeline and the cache would be decorative.
    // A comment cannot change what a shader does, so it cannot change its
    // identity.
    const a = generateScaffold(spec({ name: 'alpha', fragment: '// red\nreturn vec4f(1.0, 0.0, 0.0, 1.0);' }));
    const b = generateScaffold(spec({ name: 'beta', fragment: 'return vec4f(1.0, 0.0, 0.0, 1.0); // a much longer explanation of the same thing' }));
    expect(a.code).not.toBe(b.code);
    expect(a.pipelineKey).toBe(b.pipelineKey);
    expect(a.pipelineStateKey).toBe(b.pipelineStateKey);
  });

  test('a real code change still separates the pipeline', () => {
    // ...and stripping comments must not go so far as to equate programs that
    // differ. If it did, two materials would be drawn with the wrong shader.
    const a = generateScaffold(spec({ fragment: 'return vec4f(1.0, 0.0, 0.0, 1.0);' }));
    const b = generateScaffold(spec({ fragment: 'return vec4f(1.0, 0.0, 0.0, 0.5);' }));
    expect(a.pipelineKey).not.toBe(b.pipelineKey);
  });

  test('removeComments deletes rather than blanks, so a long comment cannot shift the hash', () => {
    // Blanking would leave a run of spaces and still change the hash. Deleting
    // is what makes comment length irrelevant.
    // Whitespace that merely preceded a comment stays — deleting it would
    // mean tracking whether it was separating two tokens, which is the
    // tokenizer's job and not the key's.
    expect(removeComments('a // x\nb')).toBe('a \nb');
    expect(removeComments('a /* x */ b')).toBe('a  b');
    expect(removeComments('a\n// whole line\nb')).toBe('a\n\nb');
    expect(removeComments('a;')).not.toBe(removeComments('b;'));

    // tokenKeyOf is the form actually hashed, and it drops the leftover runs.
    expect(tokenKeyOf('a // x\n b')).toBe('a b');
    expect(tokenKeyOf('a  /* x */   b')).toBe('a b');
    expect(tokenKeyOf('a /* a much longer comment */ b')).toBe(tokenKeyOf('a // x\n b'));
    // ...and a token change is still visible.
    expect(tokenKeyOf('a;')).not.toBe(tokenKeyOf('b;'));
  });

  test('a different material with the same name is a different pipeline', () => {
    const a = generateScaffold(spec({ name: 'x', slots: { a: 'f32' } }));
    const b = generateScaffold(spec({ name: 'x', slots: { b: 'f32' } }));
    expect(a.pipelineKey).not.toBe(b.pipelineKey);
    expect(a.pipelineStateKey).not.toBe(b.pipelineStateKey);
  });
});

// ---------------------------------------------------------------------------
// describeMaterial — the anti-hallucination surface
// ---------------------------------------------------------------------------

describe('describeMaterial', () => {
  const d = describeMaterial(CHECKER);

  test('it inventories every slot with its type, offset, and how to read it', () => {
    expect(d.slots).toEqual([
      { name: 'baseColor', type: 'vec3f', wgsl: 'vec3<f32>', components: 3, offset: 0, size: 12, access: 'mat.baseColor' },
      { name: 'scale', type: 'f32', wgsl: 'f32', components: 1, offset: 12, size: 4, access: 'mat.scale' },
    ]);
  });

  test('it inventories every varying with its location, and marks the builtin', () => {
    expect(d.varyings).toEqual([
      { name: 'clip', type: 'vec4f', location: -1, flat: false, builtin: true },
      { name: 'worldPos', type: 'vec3f', location: 0, flat: false, builtin: false },
      { name: 'uv', type: 'vec2f', location: 1, flat: false, builtin: false },
    ]);
  });

  test('it inventories every texture with its view dimension and its sampler', () => {
    expect(d.textures).toEqual([{
      slotName: 'albedo',
      varName: 'albedo',
      kind: '2d',
      viewDimension: '2d',
      sampleType: 'float',
      binding: 0,
      sampler: 'albedoSampler',
      samplerBinding: 1,
      samplerSharedWith: [],
      declaration: '@group(3) @binding(0) var albedo : texture_2d<f32>;',
    }]);
  });

  test('it reports which slots share a sampler, so the correct name is never guessed', () => {
    const shared = describeMaterial(spec({ textures: { albedo: { kind: '2d' }, normalMap: { kind: '2d' } } }));
    expect(shared.textures.find((t) => t.slotName === 'normalMap')).toMatchObject({
      sampler: 'albedoSampler',
      samplerBinding: 2,
      samplerSharedWith: ['albedo'],
    });
    expect(shared.samplers).toEqual([{
      name: 'albedoSampler',
      binding: 2,
      type: 'sampler',
      sharedBy: ['albedo', 'normalMap'],
    }]);
  });

  test('it reports the full bind group layout, including absent groups', () => {
    expect(d.bindGroups.map((g) => [g.index, g.name, g.present])).toEqual([
      [0, 'frame', true],
      [1, 'object', true],
      [2, 'material', true],
      [3, 'texture', true],
    ]);
    expect(d.bindGroups[3].entries).toEqual([
      { binding: 0, resource: '2d / float (2d)', visibility: 'VERTEX | FRAGMENT' },
      { binding: 1, resource: 'sampler sampler (repeat, mipmapped)', visibility: 'VERTEX | FRAGMENT' },
    ]);
  });

  test('an untextured, slotless material reports groups 2 and 3 as absent', () => {
    const bare = describeMaterial(spec());
    expect(bare.bindGroups[2].present).toBe(false);
    expect(bare.bindGroups[3].present).toBe(false);
    expect(bare.blocks.material).toBeNull();
    expect(bare.textures).toEqual([]);
  });

  test('it reports block sizes, including the object stride a dynamic offset needs', () => {
    expect(d.blocks.frame).toEqual({ name: 'Frame', size: FRAME_BLOCK.size, fields: 14 });
    expect(d.blocks.object).toEqual({ name: 'ObjectData', size: OBJECT_BLOCK.size, stride: OBJECT_BLOCK.stride, fields: 5 });
    expect(d.blocks.material).toEqual({ name: 'MaterialData', size: 16, fields: 2 });
  });

  test('it states exactly what each body may reference', () => {
    expect(d.bodyNames.vertex).toEqual(['in', 'frame', 'obj', 'out', 'mat', 'albedo', 'albedoSampler']);
    expect(d.bodyNames.fragment).toEqual(['in', 'frame', 'obj', 'mat', 'albedo', 'albedoSampler']);
  });

  test('it reports the WGSL length, so a size regression is visible', () => {
    expect(d.wgslBytes).toBe(GOLDEN_WGSL.length);
  });

  test('it reports the resolved fixed-function state and the keys', () => {
    expect(d.state).toEqual({
      phase: 'opaque',
      topology: 'triangle-list',
      cull: 'back',
      frontFace: 'ccw',
      depth: { write: true, compare: 'less' },
      blend: null,
      targets: [{ format: 'bgra8unorm', blend: null, writeMask: 15 }],
      sampleCount: 1,
      depthFormat: 'depth24plus',
    });
    expect(d.pipelineStateKey).toBe(generateScaffold(CHECKER).pipelineStateKey);
    expect(d.pipelineKey).toBe(generateScaffold(CHECKER).pipelineKey);
  });

  test('it is memoised, so calling it per frame in a dev build is a map lookup', () => {
    expect(describeMaterial(CHECKER)).toBe(d);
  });

  test('it works with no device at all — which is the whole point', () => {
    // Every field above came from a spec and a device-free generator. An agent
    // can call this instead of reading source.
    expect(typeof globalThis.navigator === 'undefined' || (globalThis.navigator as { gpu?: unknown }).gpu === undefined).toBe(true);
    expect(d.name).toBe('checker');
  });
});

// ---------------------------------------------------------------------------
// Structural validation of generated WGSL
// ---------------------------------------------------------------------------

describe('validateGeneratedWGSL', () => {
  test('it accepts every material this module ships', () => {
    for (const s of [
      CHECKER,
      basicMaterialSpec(),
      basicMaterialSpec({ textured: true, transparent: true, doubleSided: true }),
      pbrMaterialSpec(),
      pbrMaterialSpec({ shadows: true }),
      spec({ textures: { a: { kind: 'cube' }, b: { kind: '3d' }, c: { kind: '2d-array' } } }),
      spec({ layout: layout({ position: 'float32x3', normal: 'float32x3' }) }),
    ]) {
      expect(() => validateGeneratedWGSL(generateScaffold(s).code)).not.toThrow();
    }
  });

  test('it rejects an unbalanced brace', () => {
    expectError(() => validateGeneratedWGSL('struct A {\n  f : f32,\n'), 'INTERNAL_INVARIANT');
    expectError(() => validateGeneratedWGSL('}'), 'INTERNAL_INVARIANT');
    // ...and a balanced one is accepted, or the check would be useless.
    expect(() => validateGeneratedWGSL('struct A {\n  f : f32,\n};')).not.toThrow();
  });

  test('it rejects a struct field with no trailing comma', () => {
    const err = expectError(() => validateGeneratedWGSL('struct A {\n  f : f32\n};'), 'INTERNAL_INVARIANT');
    expect(err.message).toContain('trailing comma');
  });

  test('it rejects a binding at a group that is not in BIND_GROUP', () => {
    const err = expectError(
      () => validateGeneratedWGSL('@group(7) @binding(0) var x : sampler;'),
      'INTERNAL_INVARIANT',
    );
    expect(err.message).toContain('@group(7)');
    expect(err.why).toContain('BIND_GROUP');
  });

  test('it rejects a group exposing the wrong variable', () => {
    // Positional layouts: @group(0) must be `frame`, or the renderer's bind
    // group for group 0 would be described against the wrong thing.
    const err = expectError(
      () => validateGeneratedWGSL('@group(0) @binding(0) var<uniform> notframe : Frame;'),
      'INTERNAL_INVARIANT',
    );
    expect(err.message).toContain('must be "frame"');
  });
});

// ---------------------------------------------------------------------------
// The two shipped materials
// ---------------------------------------------------------------------------

describe('basic and pbr go through the same scaffold', () => {
  test('basic is unlit, tiny, and needs no hand-written WGSL', () => {
    const s = basicMaterialSpec();
    const statements = (src: string | undefined): string[] =>
      stripComments(src ?? '').split('\n').map((l) => l.trim()).filter((l) => l.length > 0);
    expect(Object.keys(s.slots ?? {})).toEqual(['tint', 'opacity']);
    expect(statements(s.vertex)).toEqual([
      'out.clip = frame.viewProj * obj.model * vec4f(in.position, 1.0);',
      'out.uv = in.uv;',
    ]);
    expect(statements(s.fragment)).toEqual(['return vec4f(mat.tint, mat.opacity * frame.alpha);']);
    expect(s.textures).toBeUndefined();
  });

  test('the transparent variant defaults to no depth write and alpha blending', () => {
    const s = basicMaterialSpec({ transparent: true });
    expect(s.phase).toBe('transparent');
    expect(s.depth).toEqual({ write: false, compare: 'less' });
    expect(s.blend?.color).toEqual({ srcFactor: 'src-alpha', dstFactor: 'one-minus-src-alpha', operation: 'add' });
  });

  test('the opaque variant replaces rather than blends', () => {
    expect(basicMaterialSpec().blend).toBeNull();
  });

  test('pbr declares the seven required slots, plus the two the shadow needs', () => {
    const s = pbrMaterialSpec();
    expect(s.slots).toMatchObject({
      baseColor: { type: 'vec3f' },
      metallic: { type: 'f32' },
      roughness: { type: 'f32' },
      lightDir: { type: 'vec3f' },
      lightColor: { type: 'vec3f' },
      ambientColor: { type: 'vec3f' },
      aoStrength: { type: 'f32' },
    });
  });

  test('pbr options become slot defaults, so setSlot can retune them later', () => {
    const s = pbrMaterialSpec({ baseColor: [1, 0, 0], metallic: 0.9, roughness: 0.2 });
    expect(s.slots?.baseColor).toEqual({ type: 'vec3f', default: [1, 0, 0] });
    expect(s.slots?.metallic).toEqual({ type: 'f32', default: 0.9 });
  });

  test('pbr without shadows declares no texture group at all', () => {
    const g = generateScaffold(pbrMaterialSpec());
    expect(g.textureSlots).toEqual([]);
    expect(g.resolved.samplers).toEqual([]);
    expect(g.code).not.toContain('@group(3)');
    expect(g.code).not.toContain('textureSampleCompare');
  });

  test('pbr with shadows declares a depth texture and a comparison sampler', () => {
    const g = generateScaffold(pbrMaterialSpec({ shadows: true }));
    expect(g.textureSlots[0]).toMatchObject({ kind: 'depth-2d', sampleType: 'depth', compare: true });
    expect(g.resolved.samplers[0].wgslType).toBe('sampler_comparison');
    expect(g.code).toContain('@group(3) @binding(0) var shadowDepth : texture_depth_2d;');
    expect(g.code).toContain('textureSampleCompare(shadowDepth, shadowDepthSampler');
  });

  test('pbr keeps the comparison sample in uniform control flow', () => {
    // textureSampleCompare is illegal in non-uniform control flow. The bounds
    // test is folded into `select` for exactly this reason, and this test is
    // what stops someone "simplifying" it back into an early-out.
    const code = generateScaffold(pbrMaterialSpec({ shadows: true })).code;
    const body = code.slice(code.indexOf('fn fs('));
    expect(body).toContain('let shadow = select(1.0, sum / 9.0, inside);');
    expect(body).not.toMatch(/\n\s*if\s*\([^)]*shadowUV[^)]*\)\s*\{[^}]*textureSampleCompare/);
  });

  test('pbr uses a mat3x3f by mat3x3f, not a GLSL mat3 by vec4', () => {
    // WGSL is strict: matCxR multiplies a vecC. This is a classic porting slip
    // and the generated shader must not make it.
    const code = generateScaffold(pbrMaterialSpec()).code;
    expect(code).toContain('normalize(obj.normalMatrix * in.normal)');
    expect(code).not.toContain('obj.normalMatrix * vec4f');
  });

  test('both materials produce structurally valid programs', () => {
    for (const s of [basicMaterialSpec({ textured: true }), pbrMaterialSpec({ shadows: true })]) {
      parseCheck(s);
    }
  });

  test('pbr and basic each compile to a distinct pipeline but share nothing by accident', () => {
    const a = generateScaffold(basicMaterialSpec());
    const b = generateScaffold(pbrMaterialSpec());
    expect(a.pipelineStateKey).not.toBe(b.pipelineStateKey);
    // ...but they do share the frame and object layouts, because the state key
    // is per-material structural identity while the *layouts* are keyed by
    // their own signature in the device cache.
    expect(a.resolved.layout.key).toBe(b.resolved.layout.key);
  });
});
